-- BVS final sprint core compatibility migration. Safe to rerun.
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check
  check (role in ('listener','artist','writer','show_creator','moderator','admin'));

alter table public.tracks add column if not exists explicit_content boolean not null default false;

create table if not exists public.track_play_events (
  id bigint generated by default as identity primary key,
  track_id uuid not null references public.tracks(id) on delete cascade,
  source text not null default 'station'
    check (source in ('station', 'catalogue', 'artist', 'embed')),
  created_at timestamptz not null default now()
);

create index if not exists track_play_events_track_created_idx
  on public.track_play_events(track_id, created_at desc);
create index if not exists track_play_events_created_idx
  on public.track_play_events(created_at desc);

alter table public.track_play_events enable row level security;

create or replace function public.record_track_play(p_track_id uuid, p_source text default 'station')
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.track_play_events(track_id, source)
  values (
    p_track_id,
    case when p_source in ('station','catalogue','artist','embed') then p_source else 'station' end
  );

  update public.tracks
  set play_count = coalesce(play_count, 0) + 1
  where id = p_track_id
    and is_public = true
    and editorial_status = 'approved';
end;
$$;
alter table public.orders add column if not exists customer_user_id uuid references auth.users(id) on delete set null;
alter table public.orders add column if not exists tax_amount numeric(10,2) not null default 0;
alter table public.orders add column if not exists tax_rate numeric(8,6) not null default 0;
alter table public.orders add column if not exists tax_mode varchar(40);
alter table public.orders add column if not exists tax_country varchar(8);
alter table public.orders add column if not exists stripe_session_id text;
alter table public.orders add column if not exists stripe_payment_intent text;
create index if not exists orders_customer_user_idx on public.orders(customer_user_id, created_at desc);
create index if not exists orders_stripe_session_idx on public.orders(stripe_session_id) where stripe_session_id is not null;

-- Prevent duplicate credits if webhook requests race.
create unique index if not exists artist_ledger_one_deposit_credit
  on public.artist_ledger_entries(deposit_id, entry_type)
  where deposit_id is not null and entry_type = 'deposit_credit';
