-- BVS Live Phase 1 — beta/staging only.
-- Apply only to the isolated beta Supabase project.
-- No production migration is authorized while Apple Review is open.

create table if not exists public.show_streams (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null unique references public.show_events(id) on delete cascade,
  creator_id uuid null references auth.users(id) on delete set null,
  public_id text not null unique
    check (public_id ~ '^evt_[a-z0-9]{8,16}$'),
  playback_id text not null unique
    check (playback_id ~ '^[a-z0-9_-]{8,48}$'),
  stream_key_hash text not null
    check (stream_key_hash ~ '^[a-f0-9]{64}$'),
  key_active boolean not null default true,
  revoked_at timestamptz null,
  status text not null default 'draft'
    check (status in ('draft','ready','connecting','live','interrupted','ended','processing','archived')),
  valid_from timestamptz null,
  valid_until timestamptz null,
  media_origin_id text null,
  active_client_id text null,
  active_server_id text null,
  live_playback_url text null,
  last_publish_at timestamptz null,
  last_unpublish_at timestamptz null,
  started_at timestamptz null,
  ended_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (valid_until is null or valid_from is null or valid_until > valid_from),
  check (live_playback_url is null or live_playback_url ~ '^https://')
);

create table if not exists public.show_stream_events (
  id bigint generated by default as identity primary key,
  stream_id uuid not null references public.show_streams(id) on delete cascade,
  type text not null
    check (type in ('publish_accepted','publish_rejected','unpublish','stale_unpublish_ignored')),
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists show_streams_event_idx
  on public.show_streams(event_id);
create index if not exists show_streams_public_id_idx
  on public.show_streams(public_id);
create index if not exists show_streams_status_idx
  on public.show_streams(status, updated_at desc);
create index if not exists show_stream_events_stream_time_idx
  on public.show_stream_events(stream_id, occurred_at desc);

alter table public.show_streams enable row level security;
alter table public.show_stream_events enable row level security;

revoke all on table public.show_streams, public.show_stream_events from public, anon, authenticated;
grant select, insert, update, delete on table public.show_streams, public.show_stream_events to service_role;
grant usage, select on sequence public.show_stream_events_id_seq to service_role;

-- Atomic media-truth transition after the route has authenticated the stream secret.
-- The function repeats lifecycle/window checks under row locks to close races.
create or replace function public.bvs_live_mark_published(
  p_stream_id uuid,
  p_client_id text,
  p_server_id text,
  p_playback_url text
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  s public.show_streams%rowtype;
  e public.show_events%rowtype;
  v_now timestamptz := now();
begin
  if coalesce(btrim(p_client_id), '') = '' then
    return 'not_ready';
  end if;
  if p_playback_url is null or p_playback_url !~ '^https://' then
    return 'not_ready';
  end if;

  select * into s
  from public.show_streams
  where id = p_stream_id
  for update;

  if not found then
    return 'unknown_stream';
  end if;

  if s.key_active is not true or s.revoked_at is not null then
    return 'inactive_key';
  end if;
  if s.status not in ('ready', 'live') then
    return 'not_ready';
  end if;
  if s.valid_from is not null and v_now < s.valid_from then
    return 'window';
  end if;
  if s.valid_until is not null and v_now > s.valid_until then
    return 'window';
  end if;

  select * into e
  from public.show_events
  where id = s.event_id
  for update;

  if not found then
    return 'no_event';
  end if;
  if e.status not in ('scheduled', 'live') then
    return 'event_blocked';
  end if;

  update public.show_streams
  set status = 'live',
      active_client_id = p_client_id,
      active_server_id = nullif(btrim(coalesce(p_server_id, '')), ''),
      live_playback_url = p_playback_url,
      last_publish_at = v_now,
      started_at = coalesce(started_at, v_now),
      ended_at = null,
      updated_at = v_now
  where id = s.id;

  update public.show_events
  set status = 'live',
      live_video_url = p_playback_url,
      updated_at = v_now
  where id = e.id;

  insert into public.show_stream_events(stream_id, type, metadata, occurred_at)
  values (
    s.id,
    'publish_accepted',
    jsonb_strip_nulls(jsonb_build_object('client_id', p_client_id, 'server_id', nullif(btrim(coalesce(p_server_id, '')), ''))),
    v_now
  );

  return 'accepted';
end;
$$;

-- End only the currently active SRS publisher. A stale disconnect from an
-- older client is acknowledged but cannot end a replacement connection.
create or replace function public.bvs_live_mark_unpublished(
  p_stream_id uuid,
  p_client_id text
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  s public.show_streams%rowtype;
  v_now timestamptz := now();
begin
  select * into s
  from public.show_streams
  where id = p_stream_id
  for update;

  if not found then
    return 'noop';
  end if;

  if s.status in ('ended', 'archived', 'processing') then
    return 'noop';
  end if;

  -- A rejected/never-live publish must not turn a ready stream into ended.
  if s.status <> 'live' then
    return 'noop';
  end if;

  if coalesce(s.active_client_id, '') <> coalesce(p_client_id, '') then
    insert into public.show_stream_events(stream_id, type, metadata, occurred_at)
    values (
      s.id,
      'stale_unpublish_ignored',
      jsonb_build_object('client_id', coalesce(p_client_id, '')),
      v_now
    );
    return 'stale';
  end if;

  update public.show_streams
  set status = 'ended',
      active_client_id = null,
      active_server_id = null,
      last_unpublish_at = v_now,
      ended_at = v_now,
      updated_at = v_now
  where id = s.id;

  -- Do not overwrite a concurrent editorial cancellation/archive.
  update public.show_events
  set status = 'ended',
      updated_at = v_now
  where id = s.event_id
    and status = 'live';

  insert into public.show_stream_events(stream_id, type, metadata, occurred_at)
  values (s.id, 'unpublish', jsonb_build_object('client_id', coalesce(p_client_id, '')), v_now);

  return 'ended';
end;
$$;

revoke execute on function public.bvs_live_mark_published(uuid, text, text, text) from public, anon, authenticated;
revoke execute on function public.bvs_live_mark_unpublished(uuid, text) from public, anon, authenticated;
grant execute on function public.bvs_live_mark_published(uuid, text, text, text) to service_role;
grant execute on function public.bvs_live_mark_unpublished(uuid, text) to service_role;
