import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Refunds and cancellations',
  description: 'BVS Radio refund, cancellation and digital-delivery policy.',
}

export default function RefundsPage() {
  return <main className="mx-auto max-w-4xl px-6 py-12"><section className="rounded-2xl border border-white/10 bg-bg-card/50 p-8 md:p-12"><h1 className="text-4xl font-semibold">Refunds and cancellations</h1><p className="mt-3 text-text-secondary">Last updated: 26 July 2026</p><div className="mt-8 space-y-7 leading-relaxed text-text-secondary"><section><h2 className="text-2xl font-semibold text-text-primary">Digital music and beat licences</h2><p className="mt-2">Before delivery begins, contact BVS as quickly as possible to request cancellation. After a downloadable file or licence has been delivered, refunds are normally unavailable because digital performance has begun, except where the file is defective, materially different from its listing, duplicated, or consumer law requires a remedy.</p></section><section><h2 className="text-2xl font-semibold text-text-primary">Studio services</h2><p className="mt-2">A service may be cancelled before work starts. If work has started, BVS may retain the reasonable value of work already completed and refund any unused balance. Custom work, approved milestones and delivered revisions are handled according to the quote and project record.</p></section><section><h2 className="text-2xl font-semibold text-text-primary">Beat exclusives</h2><p className="mt-2">Exclusive licences require human confirmation that the beat remains available. If an exclusive cannot be supplied, BVS will cancel and refund the exclusive payment. Non-exclusive licences already delivered remain governed by the licence snapshot shown on the receipt.</p></section><section><h2 className="text-2xl font-semibold text-text-primary">Failed or duplicate payments</h2><p className="mt-2">BVS will investigate duplicate charges, payment confirmed without delivery, corrupt files and incorrect totals. Keep the order reference and contact us from the purchase email.</p></section><section><h2 className="text-2xl font-semibold text-text-primary">How to request help</h2><p className="mt-2">Use the <Link href="/contact?topic=account" className="text-brand">contact form</Link> and include the order reference. This policy does not limit mandatory consumer rights that apply in your country.</p></section></div></section></main>
}
