-- ============================================================
-- BVS pack 02-analytics
-- Source: supabase-analytics.sql
-- Project: rdwwyolrxahimcgpkzzy
-- Paste entire file into SQL Editor → Run
-- ============================================================

-- First-party, privacy-conscious product analytics for BVS Radio.
-- No IP address, user-agent, email, payment details, or persistent device ID is stored.
CREATE TABLE IF NOT EXISTS public.analytics_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name TEXT NOT NULL CHECK (event_name IN (
    'player_start', 'listening_duration', 'search_no_results', 'track_save',
    'upload_complete', 'checkout_started', 'checkout_redirect',
    'checkout_complete', 'playback_error', 'payment_error'
  )),
  session_id TEXT,
  path TEXT,
  properties JSONB NOT NULL DEFAULT '{}'::jsonb,
  source TEXT NOT NULL DEFAULT 'web' CHECK (source IN ('web', 'server')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS analytics_events_name_created_idx ON public.analytics_events(event_name, created_at DESC);
CREATE INDEX IF NOT EXISTS analytics_events_created_idx ON public.analytics_events(created_at DESC);
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;
-- No browser policies: only the service-role API can read or write this table.

CREATE OR REPLACE FUNCTION public.prune_old_analytics_events()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  DELETE FROM public.analytics_events WHERE created_at < NOW() - INTERVAL '90 days';
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS prune_old_analytics_events_after_insert ON public.analytics_events;
CREATE TRIGGER prune_old_analytics_events_after_insert
  AFTER INSERT ON public.analytics_events
  FOR EACH STATEMENT EXECUTE FUNCTION public.prune_old_analytics_events();

CREATE OR REPLACE VIEW public.analytics_daily_summary WITH (security_invoker = true) AS
SELECT date_trunc('day', created_at) AS day, event_name, count(*) AS events,
       count(DISTINCT session_id) FILTER (WHERE session_id IS NOT NULL) AS sessions
FROM public.analytics_events
GROUP BY 1, 2 ORDER BY 1 DESC, 2;

CREATE OR REPLACE VIEW public.analytics_recent_errors WITH (security_invoker = true) AS
SELECT created_at, event_name, path, properties, source
FROM public.analytics_events
WHERE event_name IN ('playback_error', 'payment_error')
ORDER BY created_at DESC;
