-- ============================================================
-- BVS pack 03-editorial
-- Source: supabase-editorial-workflow.sql
-- Project: rdwwyolrxahimcgpkzzy
-- Paste entire file into SQL Editor → Run
-- ============================================================

-- BVS Radio editorial workflow and role-based permissions.
-- Safe to rerun in the Supabase SQL Editor.

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_published BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS editorial_status TEXT NOT NULL DEFAULT 'submitted'
  CHECK (editorial_status IN ('submitted', 'in_review', 'approved', 'rejected'));
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS editorial_notes TEXT;
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS explicit_content BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS reviewed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ;
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS in_rotation BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS rotation_added_at TIMESTAMPTZ;
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS licence_type TEXT NOT NULL DEFAULT 'not_for_sale'
  CHECK (licence_type IN ('not_for_sale', 'personal_download', 'standard_lease', 'exclusive', 'custom'));
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS licence_summary TEXT;

CREATE TABLE IF NOT EXISTS public.editorial_staff (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('administrator', 'editor', 'programmer', 'credits_editor', 'commerce_manager')),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  appointed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.programmes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  tagline TEXT,
  description TEXT,
  host TEXT NOT NULL DEFAULT 'BVS Radio',
  image_url TEXT,
  day_label TEXT NOT NULL,
  start_time TIME,
  timezone TEXT NOT NULL DEFAULT 'Africa/Harare',
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'scheduled', 'active', 'archived')),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.track_credits (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  track_id UUID NOT NULL REFERENCES public.tracks(id) ON DELETE CASCADE,
  person_name TEXT NOT NULL,
  credit_role TEXT NOT NULL,
  profile_url TEXT,
  is_verified BOOLEAN NOT NULL DEFAULT TRUE,
  verified_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(track_id, person_name, credit_role)
);

CREATE TABLE IF NOT EXISTS public.editorial_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS tracks_editorial_status_idx ON public.tracks(editorial_status, created_at DESC);
CREATE INDEX IF NOT EXISTS tracks_rotation_idx ON public.tracks(in_rotation, is_public);

CREATE TABLE IF NOT EXISTS public.track_review_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  track_id UUID NOT NULL REFERENCES public.tracks(id) ON DELETE CASCADE,
  artist_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  request_type TEXT NOT NULL CHECK (request_type IN ('takedown','metadata_correction','artwork_replacement','rights_update','payout_question','other')),
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','reviewing','resolved','rejected')),
  staff_notes TEXT,
  reviewed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS track_review_requests_artist_created_idx
  ON public.track_review_requests(artist_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS track_review_requests_status_created_idx
  ON public.track_review_requests(status, created_at DESC);

ALTER TABLE public.track_review_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "artists manage own track requests" ON public.track_review_requests;
CREATE POLICY "artists manage own track requests"
  ON public.track_review_requests
  FOR ALL
  USING (artist_user_id = auth.uid())
  WITH CHECK (artist_user_id = auth.uid());
CREATE INDEX IF NOT EXISTS programmes_status_idx ON public.programmes(status, day_label, start_time);
CREATE INDEX IF NOT EXISTS editorial_audit_created_idx ON public.editorial_audit_log(created_at DESC);

ALTER TABLE public.editorial_staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.programmes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.track_credits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.editorial_audit_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Published programmes are public" ON public.programmes;
CREATE POLICY "Published programmes are public" ON public.programmes FOR SELECT
  USING (status IN ('scheduled', 'active'));
DROP POLICY IF EXISTS "Verified credits are public" ON public.track_credits;
CREATE POLICY "Verified credits are public" ON public.track_credits FOR SELECT USING (is_verified = TRUE);

-- Bootstrap the first administrator after running this migration:
-- UPDATE public.profiles SET role = 'admin' WHERE username = 'YOUR_USERNAME';
-- INSERT INTO public.editorial_staff (user_id, role)
-- SELECT id, 'administrator' FROM public.profiles WHERE username = 'YOUR_USERNAME'
-- ON CONFLICT (user_id) DO UPDATE SET role = 'administrator', active = TRUE;
