-- BVS ALL packs 01-08 (library → final-sprint). One Run if preferred.
-- If it errors mid-way, re-run individual packs from the failure point.

-- ============================================================
-- BVS pack 01-library-sync
-- Source: supabase-library-sync.sql
-- Project: rdwwyolrxahimcgpkzzy
-- Paste entire file into SQL Editor → Run
-- ============================================================

-- BVS Radio account library sync migration
-- Run once in Supabase SQL Editor before enabling the deployed sync client.

CREATE TABLE IF NOT EXISTS public.user_library_items (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  section VARCHAR(20) NOT NULL CHECK (section IN ('favourites', 'follows', 'history')),
  item_id TEXT NOT NULL,
  item JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, section, item_id)
);

CREATE INDEX IF NOT EXISTS idx_user_library_items_user_section_updated
  ON public.user_library_items(user_id, section, updated_at DESC);

ALTER TABLE public.user_library_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own library" ON public.user_library_items;
DROP POLICY IF EXISTS "Users can add to own library" ON public.user_library_items;
DROP POLICY IF EXISTS "Users can update own library" ON public.user_library_items;
DROP POLICY IF EXISTS "Users can remove from own library" ON public.user_library_items;

CREATE POLICY "Users can read own library" ON public.user_library_items
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can add to own library" ON public.user_library_items
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own library" ON public.user_library_items
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can remove from own library" ON public.user_library_items
  FOR DELETE USING (auth.uid() = user_id);



-- ============================================================
-- BVS pack 02-analytics
-- Source: supabase-analytics.sql
-- Project: rdwwyolrxahimcgpkzzy
-- Paste entire file into SQL Editor → Run
-- ============================================================

-- First-party, privacy-conscious product analytics for BVS Radio.
-- No IP address, user-agent, email, payment details, or persistent device ID is stored.
CREATE TABLE IF NOT EXISTS public.analytics_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name TEXT NOT NULL CHECK (event_name IN (
    'player_start', 'listening_duration', 'search_no_results', 'track_save',
    'upload_complete', 'checkout_started', 'checkout_redirect',
    'checkout_complete', 'playback_error', 'payment_error'
  )),
  session_id TEXT,
  path TEXT,
  properties JSONB NOT NULL DEFAULT '{}'::jsonb,
  source TEXT NOT NULL DEFAULT 'web' CHECK (source IN ('web', 'server')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS analytics_events_name_created_idx ON public.analytics_events(event_name, created_at DESC);
CREATE INDEX IF NOT EXISTS analytics_events_created_idx ON public.analytics_events(created_at DESC);
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;
-- No browser policies: only the service-role API can read or write this table.

CREATE OR REPLACE FUNCTION public.prune_old_analytics_events()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  DELETE FROM public.analytics_events WHERE created_at < NOW() - INTERVAL '90 days';
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS prune_old_analytics_events_after_insert ON public.analytics_events;
CREATE TRIGGER prune_old_analytics_events_after_insert
  AFTER INSERT ON public.analytics_events
  FOR EACH STATEMENT EXECUTE FUNCTION public.prune_old_analytics_events();

CREATE OR REPLACE VIEW public.analytics_daily_summary WITH (security_invoker = true) AS
SELECT date_trunc('day', created_at) AS day, event_name, count(*) AS events,
       count(DISTINCT session_id) FILTER (WHERE session_id IS NOT NULL) AS sessions
FROM public.analytics_events
GROUP BY 1, 2 ORDER BY 1 DESC, 2;

CREATE OR REPLACE VIEW public.analytics_recent_errors WITH (security_invoker = true) AS
SELECT created_at, event_name, path, properties, source
FROM public.analytics_events
WHERE event_name IN ('playback_error', 'payment_error')
ORDER BY created_at DESC;



-- ============================================================
-- BVS pack 03-editorial
-- Source: supabase-editorial-workflow.sql
-- Project: rdwwyolrxahimcgpkzzy
-- Paste entire file into SQL Editor → Run
-- ============================================================

-- BVS Radio editorial workflow and role-based permissions.
-- Safe to rerun in the Supabase SQL Editor.

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_published BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS editorial_status TEXT NOT NULL DEFAULT 'submitted'
  CHECK (editorial_status IN ('submitted', 'in_review', 'approved', 'rejected'));
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS editorial_notes TEXT;
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS explicit_content BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS reviewed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ;
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS in_rotation BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS rotation_added_at TIMESTAMPTZ;
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS licence_type TEXT NOT NULL DEFAULT 'not_for_sale'
  CHECK (licence_type IN ('not_for_sale', 'personal_download', 'standard_lease', 'exclusive', 'custom'));
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS licence_summary TEXT;

CREATE TABLE IF NOT EXISTS public.editorial_staff (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('administrator', 'editor', 'programmer', 'credits_editor', 'commerce_manager')),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  appointed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.programmes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  tagline TEXT,
  description TEXT,
  host TEXT NOT NULL DEFAULT 'BVS Radio',
  image_url TEXT,
  day_label TEXT NOT NULL,
  start_time TIME,
  timezone TEXT NOT NULL DEFAULT 'Africa/Harare',
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'scheduled', 'active', 'archived')),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.track_credits (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  track_id UUID NOT NULL REFERENCES public.tracks(id) ON DELETE CASCADE,
  person_name TEXT NOT NULL,
  credit_role TEXT NOT NULL,
  profile_url TEXT,
  is_verified BOOLEAN NOT NULL DEFAULT TRUE,
  verified_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(track_id, person_name, credit_role)
);

CREATE TABLE IF NOT EXISTS public.editorial_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS tracks_editorial_status_idx ON public.tracks(editorial_status, created_at DESC);
CREATE INDEX IF NOT EXISTS tracks_rotation_idx ON public.tracks(in_rotation, is_public);

CREATE TABLE IF NOT EXISTS public.track_review_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  track_id UUID NOT NULL REFERENCES public.tracks(id) ON DELETE CASCADE,
  artist_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  request_type TEXT NOT NULL CHECK (request_type IN ('takedown','metadata_correction','artwork_replacement','rights_update','payout_question','other')),
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','reviewing','resolved','rejected')),
  staff_notes TEXT,
  reviewed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS track_review_requests_artist_created_idx
  ON public.track_review_requests(artist_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS track_review_requests_status_created_idx
  ON public.track_review_requests(status, created_at DESC);

ALTER TABLE public.track_review_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "artists manage own track requests" ON public.track_review_requests;
CREATE POLICY "artists manage own track requests"
  ON public.track_review_requests
  FOR ALL
  USING (artist_user_id = auth.uid())
  WITH CHECK (artist_user_id = auth.uid());
CREATE INDEX IF NOT EXISTS programmes_status_idx ON public.programmes(status, day_label, start_time);
CREATE INDEX IF NOT EXISTS editorial_audit_created_idx ON public.editorial_audit_log(created_at DESC);

ALTER TABLE public.editorial_staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.programmes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.track_credits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.editorial_audit_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Published programmes are public" ON public.programmes;
CREATE POLICY "Published programmes are public" ON public.programmes FOR SELECT
  USING (status IN ('scheduled', 'active'));
DROP POLICY IF EXISTS "Verified credits are public" ON public.track_credits;
CREATE POLICY "Verified credits are public" ON public.track_credits FOR SELECT USING (is_verified = TRUE);

-- Bootstrap the first administrator after running this migration:
-- UPDATE public.profiles SET role = 'admin' WHERE username = 'YOUR_USERNAME';
-- INSERT INTO public.editorial_staff (user_id, role)
-- SELECT id, 'administrator' FROM public.profiles WHERE username = 'YOUR_USERNAME'
-- ON CONFLICT (user_id) DO UPDATE SET role = 'administrator', active = TRUE;



-- ============================================================
-- BVS pack 04-wallet
-- Source: supabase-artist-wallet-ledger.sql
-- Project: rdwwyolrxahimcgpkzzy
-- Paste entire file into SQL Editor → Run
-- ============================================================

-- BVS Radio artist wallet, deposits, onboarding and payout ledger foundation.
-- Safe to rerun in the Supabase SQL Editor.
--
-- This is schema-only groundwork. Application code should decide when a
-- deposit is creditable, when a ledger entry is posted, and which staff role
-- is allowed to approve payouts.

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.is_artist_wallet_admin()
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  allowed boolean;
BEGIN
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles p
    WHERE p.id = auth.uid()
      AND p.role IN ('admin', 'moderator')
  ) INTO allowed;

  IF allowed THEN
    RETURN TRUE;
  END IF;

  IF to_regclass('public.editorial_staff') IS NULL THEN
    RETURN FALSE;
  END IF;

  EXECUTE
    'SELECT EXISTS (
      SELECT 1
      FROM public.editorial_staff s
      WHERE s.user_id = auth.uid()
        AND s.active = TRUE
        AND s.role IN (''administrator'', ''commerce_manager'')
    )'
    INTO allowed;

  RETURN COALESCE(allowed, FALSE);
END;
$$;

CREATE TABLE IF NOT EXISTS public.artist_wallet_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  description TEXT,
  updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (jsonb_typeof(value) = 'object')
);

INSERT INTO public.artist_wallet_settings (key, value, description)
VALUES (
  'payout_minimum_usd',
  '{"amount": 25.00, "currency": "USD"}'::jsonb,
  'Minimum artist payout request threshold. Application code should copy this into payout_requests.minimum_amount_snapshot.'
)
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.artist_waitlist (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL,
  artist_name TEXT NOT NULL,
  contact_name TEXT,
  phone TEXT,
  country TEXT,
  city TEXT,
  links JSONB NOT NULL DEFAULT '{}'::jsonb,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'new'
    CHECK (status IN ('new', 'reviewing', 'invited', 'onboarded', 'rejected', 'archived')),
  source TEXT NOT NULL DEFAULT 'manual',
  invited_at TIMESTAMPTZ,
  onboarded_profile_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS artist_waitlist_email_lower_idx
  ON public.artist_waitlist (LOWER(email));
-- Plain unique on email so PostgREST on_conflict=email works for upserts.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'artist_waitlist_email_key'
  ) THEN
    ALTER TABLE public.artist_waitlist ADD CONSTRAINT artist_waitlist_email_key UNIQUE (email);
  END IF;
EXCEPTION
  WHEN unique_violation THEN
    NULL; -- existing duplicate emails; lower() index still enforces case-insensitive uniqueness
  WHEN duplicate_object THEN
    NULL;
END $$;
CREATE INDEX IF NOT EXISTS artist_waitlist_status_created_idx
  ON public.artist_waitlist(status, created_at DESC);

CREATE TABLE IF NOT EXISTS public.artist_onboarding_invites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  waitlist_id UUID REFERENCES public.artist_waitlist(id) ON DELETE SET NULL,
  email TEXT NOT NULL,
  artist_name TEXT,
  invite_code TEXT UNIQUE NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'accepted', 'expired', 'revoked')),
  invited_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  accepted_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  accepted_profile_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  expires_at TIMESTAMPTZ,
  accepted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS artist_onboarding_invites_email_status_idx
  ON public.artist_onboarding_invites(LOWER(email), status);
CREATE INDEX IF NOT EXISTS artist_onboarding_invites_waitlist_idx
  ON public.artist_onboarding_invites(waitlist_id);

CREATE TABLE IF NOT EXISTS public.artist_deposits (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  artist_user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'creditable', 'credited', 'refunded', 'void')),
  source TEXT NOT NULL DEFAULT 'manual'
    CHECK (source IN ('manual', 'checkout', 'paynow', 'stripe', 'bank_transfer', 'adjustment', 'other')),
  external_reference TEXT,
  order_id UUID REFERENCES public.orders(id) ON DELETE SET NULL,
  notes TEXT,
  received_at TIMESTAMPTZ,
  creditable_at TIMESTAMPTZ,
  credited_at TIMESTAMPTZ,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(source, external_reference)
);

CREATE INDEX IF NOT EXISTS artist_deposits_artist_status_idx
  ON public.artist_deposits(artist_user_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS artist_deposits_order_idx
  ON public.artist_deposits(order_id);

CREATE TABLE IF NOT EXISTS public.artist_ledger_entries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  artist_user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  direction TEXT NOT NULL CHECK (direction IN ('credit', 'debit')),
  entry_type TEXT NOT NULL CHECK (entry_type IN (
    'deposit_credit',
    'sale_credit',
    'royalty_credit',
    'manual_credit',
    'adjustment_debit',
    'refund_debit',
    'payout_debit',
    'reversal_debit'
  )),
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  status TEXT NOT NULL DEFAULT 'posted' CHECK (status IN ('pending', 'posted', 'void')),
  source_table TEXT,
  source_id UUID,
  deposit_id UUID REFERENCES public.artist_deposits(id) ON DELETE SET NULL,
  payout_request_id UUID,
  memo TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  effective_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS artist_ledger_entries_artist_effective_idx
  ON public.artist_ledger_entries(artist_user_id, effective_at DESC);
CREATE INDEX IF NOT EXISTS artist_ledger_entries_source_idx
  ON public.artist_ledger_entries(source_table, source_id);
CREATE INDEX IF NOT EXISTS artist_ledger_entries_deposit_idx
  ON public.artist_ledger_entries(deposit_id);

CREATE TABLE IF NOT EXISTS public.artist_payout_methods (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  artist_user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  method_type TEXT NOT NULL
    CHECK (method_type IN ('bank_transfer', 'paypal', 'paynow', 'mobile_money', 'cash', 'other')),
  label TEXT NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  account_holder_name TEXT,
  destination_summary TEXT,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('pending_verification', 'active', 'disabled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS artist_payout_methods_artist_status_idx
  ON public.artist_payout_methods(artist_user_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS artist_payout_methods_one_default_idx
  ON public.artist_payout_methods(artist_user_id)
  WHERE is_default = TRUE AND status <> 'disabled';

CREATE TABLE IF NOT EXISTS public.artist_payout_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  artist_user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  payout_method_id UUID REFERENCES public.artist_payout_methods(id) ON DELETE SET NULL,
  requested_amount NUMERIC(12,2) NOT NULL CHECK (requested_amount > 0),
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  minimum_amount_snapshot NUMERIC(12,2) NOT NULL DEFAULT 25.00,
  status TEXT NOT NULL DEFAULT 'requested'
    CHECK (status IN ('requested', 'approved', 'processing', 'paid', 'rejected', 'cancelled')),
  artist_note TEXT,
  staff_note TEXT,
  requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  approved_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  approved_at TIMESTAMPTZ,
  paid_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  paid_at TIMESTAMPTZ,
  payout_reference TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (requested_amount >= minimum_amount_snapshot)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'artist_ledger_entries_payout_request_fk'
      AND conrelid = 'public.artist_ledger_entries'::regclass
  ) THEN
    ALTER TABLE public.artist_ledger_entries
      ADD CONSTRAINT artist_ledger_entries_payout_request_fk
      FOREIGN KEY (payout_request_id)
      REFERENCES public.artist_payout_requests(id)
      ON DELETE SET NULL;
  END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS artist_payout_requests_artist_status_idx
  ON public.artist_payout_requests(artist_user_id, status, requested_at DESC);
CREATE INDEX IF NOT EXISTS artist_payout_requests_method_idx
  ON public.artist_payout_requests(payout_method_id);

DROP TRIGGER IF EXISTS set_artist_waitlist_updated_at ON public.artist_waitlist;
CREATE TRIGGER set_artist_waitlist_updated_at
  BEFORE UPDATE ON public.artist_waitlist
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_artist_onboarding_invites_updated_at ON public.artist_onboarding_invites;
CREATE TRIGGER set_artist_onboarding_invites_updated_at
  BEFORE UPDATE ON public.artist_onboarding_invites
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_artist_deposits_updated_at ON public.artist_deposits;
CREATE TRIGGER set_artist_deposits_updated_at
  BEFORE UPDATE ON public.artist_deposits
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_artist_payout_methods_updated_at ON public.artist_payout_methods;
CREATE TRIGGER set_artist_payout_methods_updated_at
  BEFORE UPDATE ON public.artist_payout_methods
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_artist_payout_requests_updated_at ON public.artist_payout_requests;
CREATE TRIGGER set_artist_payout_requests_updated_at
  BEFORE UPDATE ON public.artist_payout_requests
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.artist_wallet_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artist_waitlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artist_onboarding_invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artist_deposits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artist_ledger_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artist_payout_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artist_payout_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Wallet settings are readable by everyone" ON public.artist_wallet_settings;
DROP POLICY IF EXISTS "Wallet settings are admin managed" ON public.artist_wallet_settings;
CREATE POLICY "Wallet settings are readable by everyone" ON public.artist_wallet_settings
  FOR SELECT USING (true);
CREATE POLICY "Wallet settings are admin managed" ON public.artist_wallet_settings
  FOR ALL USING (public.is_artist_wallet_admin()) WITH CHECK (public.is_artist_wallet_admin());

DROP POLICY IF EXISTS "Anyone can join artist waitlist" ON public.artist_waitlist;
DROP POLICY IF EXISTS "Artist waitlist is admin readable" ON public.artist_waitlist;
DROP POLICY IF EXISTS "Artist waitlist is admin managed" ON public.artist_waitlist;
CREATE POLICY "Anyone can join artist waitlist" ON public.artist_waitlist
  FOR INSERT WITH CHECK (status = 'new');
CREATE POLICY "Artist waitlist is admin readable" ON public.artist_waitlist
  FOR SELECT USING (public.is_artist_wallet_admin());
CREATE POLICY "Artist waitlist is admin managed" ON public.artist_waitlist
  FOR UPDATE USING (public.is_artist_wallet_admin()) WITH CHECK (public.is_artist_wallet_admin());

DROP POLICY IF EXISTS "Artists can read own accepted invites" ON public.artist_onboarding_invites;
DROP POLICY IF EXISTS "Onboarding invites are admin managed" ON public.artist_onboarding_invites;
CREATE POLICY "Artists can read own accepted invites" ON public.artist_onboarding_invites
  FOR SELECT USING (accepted_by = auth.uid() OR accepted_profile_id = auth.uid());
CREATE POLICY "Onboarding invites are admin managed" ON public.artist_onboarding_invites
  FOR ALL USING (public.is_artist_wallet_admin()) WITH CHECK (public.is_artist_wallet_admin());

DROP POLICY IF EXISTS "Artists can read own deposits" ON public.artist_deposits;
DROP POLICY IF EXISTS "Artist deposits are admin managed" ON public.artist_deposits;
CREATE POLICY "Artists can read own deposits" ON public.artist_deposits
  FOR SELECT USING (artist_user_id = auth.uid());
CREATE POLICY "Artist deposits are admin managed" ON public.artist_deposits
  FOR ALL USING (public.is_artist_wallet_admin()) WITH CHECK (public.is_artist_wallet_admin());

DROP POLICY IF EXISTS "Artists can read own ledger" ON public.artist_ledger_entries;
DROP POLICY IF EXISTS "Artist ledger is admin managed" ON public.artist_ledger_entries;
CREATE POLICY "Artists can read own ledger" ON public.artist_ledger_entries
  FOR SELECT USING (artist_user_id = auth.uid() AND status = 'posted');
CREATE POLICY "Artist ledger is admin managed" ON public.artist_ledger_entries
  FOR ALL USING (public.is_artist_wallet_admin()) WITH CHECK (public.is_artist_wallet_admin());

DROP POLICY IF EXISTS "Artists can manage own payout methods" ON public.artist_payout_methods;
DROP POLICY IF EXISTS "Payout methods are admin managed" ON public.artist_payout_methods;
CREATE POLICY "Artists can manage own payout methods" ON public.artist_payout_methods
  FOR ALL USING (artist_user_id = auth.uid()) WITH CHECK (artist_user_id = auth.uid());
CREATE POLICY "Payout methods are admin managed" ON public.artist_payout_methods
  FOR ALL USING (public.is_artist_wallet_admin()) WITH CHECK (public.is_artist_wallet_admin());

DROP POLICY IF EXISTS "Artists can read own payout requests" ON public.artist_payout_requests;
DROP POLICY IF EXISTS "Artists can create own payout requests" ON public.artist_payout_requests;
DROP POLICY IF EXISTS "Artists can cancel own requested payouts" ON public.artist_payout_requests;
DROP POLICY IF EXISTS "Payout requests are admin managed" ON public.artist_payout_requests;
CREATE POLICY "Artists can read own payout requests" ON public.artist_payout_requests
  FOR SELECT USING (artist_user_id = auth.uid());
CREATE POLICY "Artists can create own payout requests" ON public.artist_payout_requests
  FOR INSERT WITH CHECK (
    artist_user_id = auth.uid()
    AND status = 'requested'
    AND requested_amount >= minimum_amount_snapshot
  );
CREATE POLICY "Artists can cancel own requested payouts" ON public.artist_payout_requests
  FOR UPDATE USING (artist_user_id = auth.uid() AND status = 'requested')
  WITH CHECK (artist_user_id = auth.uid() AND status = 'cancelled');
CREATE POLICY "Payout requests are admin managed" ON public.artist_payout_requests
  FOR ALL USING (public.is_artist_wallet_admin()) WITH CHECK (public.is_artist_wallet_admin());

-- TODO: Before production use, add RPCs or service-role API routes that:
-- - read artist_wallet_settings.payout_minimum_usd and snapshot it on payout request creation,
-- - compute available artist balance from posted ledger entries,
-- - post ledger entries atomically when deposits become creditable or payouts are paid,
-- - redact/encrypt sensitive payout method details before storing them in details JSONB.



-- ============================================================
-- BVS pack 05-releases
-- Source: supabase-releases-pipeline.sql
-- Project: rdwwyolrxahimcgpkzzy
-- Paste entire file into SQL Editor → Run
-- ============================================================

-- BVS Radio: album/EP submit → editorial publish → rotation → premium distribution shell
-- Safe to rerun in Supabase SQL Editor.

-- Premium / subscription flags on profiles
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS premium_active BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS premium_until TIMESTAMPTZ;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS distribution_enabled BOOLEAN NOT NULL DEFAULT FALSE;

-- Link tracks to a release (album/EP)
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS release_id UUID;
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS track_number INT;

CREATE TABLE IF NOT EXISTS public.releases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  artist_name TEXT NOT NULL,
  genre TEXT,
  description TEXT,
  cover_url TEXT,
  release_type TEXT NOT NULL DEFAULT 'album'
    CHECK (release_type IN ('single', 'ep', 'album', 'mixtape', 'compilation')),
  editorial_status TEXT NOT NULL DEFAULT 'submitted'
    CHECK (editorial_status IN ('submitted', 'in_review', 'approved', 'rejected')),
  editorial_notes TEXT,
  is_public BOOLEAN NOT NULL DEFAULT FALSE,
  in_rotation BOOLEAN NOT NULL DEFAULT FALSE,
  rights_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  explicit_content BOOLEAN NOT NULL DEFAULT FALSE,
  reviewed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ,
  published_at TIMESTAMPTZ,
  track_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS releases_user_created_idx ON public.releases(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS releases_status_created_idx ON public.releases(editorial_status, created_at DESC);
CREATE INDEX IF NOT EXISTS releases_public_rotation_idx ON public.releases(is_public, in_rotation);

-- Optional FK after releases exists (tracks.release_id)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'tracks_release_id_fkey'
  ) THEN
    ALTER TABLE public.tracks
      ADD CONSTRAINT tracks_release_id_fkey
      FOREIGN KEY (release_id) REFERENCES public.releases(id) ON DELETE SET NULL;
  END IF;
EXCEPTION WHEN others THEN
  NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.release_tracks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  release_id UUID NOT NULL REFERENCES public.releases(id) ON DELETE CASCADE,
  track_id UUID REFERENCES public.tracks(id) ON DELETE SET NULL,
  position INT NOT NULL DEFAULT 1,
  title TEXT NOT NULL,
  audio_path TEXT NOT NULL,
  file_url TEXT,
  duration_label TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(release_id, position)
);

CREATE INDEX IF NOT EXISTS release_tracks_release_pos_idx
  ON public.release_tracks(release_id, position);

-- Distribution job queue (partner TBD — no invented distributor)
CREATE TABLE IF NOT EXISTS public.distribution_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  release_id UUID NOT NULL REFERENCES public.releases(id) ON DELETE CASCADE,
  artist_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'not_eligible'
    CHECK (status IN (
      'not_eligible',
      'eligible',
      'queued',
      'submitted',
      'live_on_dsp',
      'failed',
      'cancelled'
    )),
  distributor TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS distribution_jobs_status_idx
  ON public.distribution_jobs(status, updated_at DESC);
CREATE INDEX IF NOT EXISTS distribution_jobs_artist_idx
  ON public.distribution_jobs(artist_user_id, created_at DESC);

ALTER TABLE public.releases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.release_tracks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.distribution_jobs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "artists manage own releases" ON public.releases;
CREATE POLICY "artists manage own releases" ON public.releases
  FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "public can read published releases" ON public.releases;
CREATE POLICY "public can read published releases" ON public.releases
  FOR SELECT USING (is_public = TRUE AND editorial_status = 'approved');

DROP POLICY IF EXISTS "artists manage own release_tracks via release" ON public.release_tracks;
CREATE POLICY "artists manage own release_tracks via release" ON public.release_tracks
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.releases r WHERE r.id = release_id AND r.user_id = auth.uid())
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM public.releases r WHERE r.id = release_id AND r.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "artists read own distribution jobs" ON public.distribution_jobs;
CREATE POLICY "artists read own distribution jobs" ON public.distribution_jobs
  FOR SELECT USING (artist_user_id = auth.uid());

-- Service role bypasses RLS for editorial/admin APIs.



-- ============================================================
-- BVS pack 06-creator
-- Source: supabase-creator-workflows.sql
-- Project: rdwwyolrxahimcgpkzzy
-- Paste entire file into SQL Editor → Run
-- ============================================================

-- BVS writer, research and show/podcast workflows.
-- Run in Supabase SQL editor, then create a private Storage bucket named show-episodes.

create extension if not exists pgcrypto;

create table if not exists public.writer_applications (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  bio text not null default '', beats text[] not null default '{}', portfolio_url text,
  status text not null default 'submitted' check (status in ('submitted','approved','rejected','paused')),
  review_notes text, reviewed_by uuid references auth.users(id), reviewed_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id)
);

create table if not exists public.editorial_articles (
  id uuid primary key default gen_random_uuid(), author_id uuid not null references auth.users(id) on delete cascade,
  title text not null, slug text, dek text not null default '', body text not null default '', sources jsonb not null default '[]'::jsonb,
  status text not null default 'draft' check (status in ('draft','submitted','in_review','changes_requested','approved','scheduled','published','rejected')),
  editor_notes text, reviewed_by uuid references auth.users(id), reviewed_at timestamptz, scheduled_for timestamptz, published_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index if not exists editorial_articles_slug_unique on public.editorial_articles(slug) where slug is not null;

create table if not exists public.research_briefs (
  id uuid primary key default gen_random_uuid(), created_by uuid not null references auth.users(id), assigned_to uuid references auth.users(id),
  topic text not null, angle text not null default '', source_links jsonb not null default '[]'::jsonb,
  findings text not null default '', seo_suggestions text not null default '',
  status text not null default 'draft' check (status in ('draft','ready_for_review','approved_for_drafting','rejected','archived')),
  reviewed_by uuid references auth.users(id), reviewed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
comment on table public.research_briefs is 'Research assistance only. Approval permits drafting, never autonomous publication.';

create table if not exists public.show_creator_profiles (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  title text not null, slug text not null unique, description text not null default '', artwork_url text, category text not null default 'Music',
  cadence text not null default 'weekly', status text not null default 'submitted' check (status in ('draft','submitted','approved','rejected','paused')),
  review_notes text, reviewed_by uuid references auth.users(id), reviewed_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, title)
);

create table if not exists public.show_episodes (
  id uuid primary key default gen_random_uuid(), show_id uuid not null references public.show_creator_profiles(id) on delete cascade,
  creator_id uuid not null references auth.users(id) on delete cascade, title text not null, description text not null default '',
  episode_number integer, audio_path text not null, duration_seconds integer, explicit boolean not null default false,
  status text not null default 'submitted' check (status in ('draft','submitted','in_review','changes_requested','approved','scheduled','published','rejected')),
  review_notes text, reviewed_by uuid references auth.users(id), reviewed_at timestamptz, scheduled_for timestamptz, published_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

alter table public.writer_applications enable row level security;
alter table public.editorial_articles enable row level security;
alter table public.research_briefs enable row level security;
alter table public.show_creator_profiles enable row level security;
alter table public.show_episodes enable row level security;

drop policy if exists "writers own application" on public.writer_applications;
create policy "writers own application" on public.writer_applications for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "writers own articles" on public.editorial_articles;
create policy "writers own articles" on public.editorial_articles for all using (auth.uid()=author_id) with check (auth.uid()=author_id);
drop policy if exists "assigned research briefs" on public.research_briefs;
create policy "assigned research briefs" on public.research_briefs for select using (auth.uid()=assigned_to or auth.uid()=created_by);
drop policy if exists "creators own shows" on public.show_creator_profiles;
create policy "creators own shows" on public.show_creator_profiles for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "creators own episodes" on public.show_episodes;
create policy "creators own episodes" on public.show_episodes for all using (auth.uid()=creator_id) with check (auth.uid()=creator_id);

create index if not exists articles_status_schedule on public.editorial_articles(status, scheduled_for);
create index if not exists episodes_status_schedule on public.show_episodes(status, scheduled_for);
create index if not exists episodes_show_created on public.show_episodes(show_id, created_at desc);



-- ============================================================
-- BVS pack 07-community
-- Source: supabase-community-chat.sql
-- Project: rdwwyolrxahimcgpkzzy
-- Paste entire file into SQL Editor → Run
-- ============================================================

-- BVS community and premium live broadcast chat.
-- Safe to rerun in the Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS public.community_memberships (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  tier TEXT NOT NULL DEFAULT 'free' CHECK (tier IN ('free', 'premium')),
  status TEXT NOT NULL DEFAULT 'inactive' CHECK (status IN ('inactive', 'active', 'past_due', 'cancelled')),
  starts_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.live_chat_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  body TEXT NOT NULL CHECK (char_length(body) BETWEEN 1 AND 500),
  broadcast_key TEXT NOT NULL DEFAULT 'bvs-live' CHECK (char_length(broadcast_key) BETWEEN 1 AND 80),
  status TEXT NOT NULL DEFAULT 'visible' CHECK (status IN ('visible', 'hidden', 'removed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  moderated_at TIMESTAMPTZ,
  moderated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.community_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reporter_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  message_id UUID NOT NULL REFERENCES public.live_chat_messages(id) ON DELETE CASCADE,
  reason TEXT NOT NULL CHECK (reason IN ('spam', 'harassment', 'hate', 'unsafe', 'other')),
  details TEXT CHECK (details IS NULL OR char_length(details) <= 500),
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'reviewing', 'resolved', 'dismissed')),
  reviewed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (reporter_id, message_id)
);

CREATE INDEX IF NOT EXISTS live_chat_messages_feed_idx
  ON public.live_chat_messages(broadcast_key, created_at DESC) WHERE status = 'visible';
CREATE INDEX IF NOT EXISTS live_chat_messages_rate_idx
  ON public.live_chat_messages(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS community_reports_status_idx
  ON public.community_reports(status, created_at DESC);

ALTER TABLE public.community_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.live_chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users read own membership" ON public.community_memberships;
CREATE POLICY "Users read own membership" ON public.community_memberships
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Signed in users read visible chat" ON public.live_chat_messages;
CREATE POLICY "Signed in users read visible chat" ON public.live_chat_messages
  FOR SELECT USING (auth.uid() IS NOT NULL AND (status = 'visible' OR auth.uid() = user_id));

DROP POLICY IF EXISTS "Premium members post live chat" ON public.live_chat_messages;
CREATE POLICY "Premium members post live chat" ON public.live_chat_messages
  FOR INSERT WITH CHECK (
    auth.uid() = user_id AND (
      EXISTS (
        SELECT 1 FROM public.community_memberships membership
        WHERE membership.user_id = auth.uid()
          AND membership.tier = 'premium'
          AND membership.status = 'active'
          AND (membership.expires_at IS NULL OR membership.expires_at > NOW())
      ) OR EXISTS (
        SELECT 1 FROM public.editorial_staff staff
        WHERE staff.user_id = auth.uid() AND staff.active = TRUE
      )
    )
  );

DROP POLICY IF EXISTS "Users create own reports" ON public.community_reports;
CREATE POLICY "Users create own reports" ON public.community_reports
  FOR INSERT WITH CHECK (auth.uid() = reporter_id);
DROP POLICY IF EXISTS "Users read own reports" ON public.community_reports;
CREATE POLICY "Users read own reports" ON public.community_reports
  FOR SELECT USING (auth.uid() = reporter_id);

-- Membership changes and moderation intentionally have no client-side policies.
-- Use the service role from trusted server/admin routes only.

-- Test premium grant (replace UUID, then remove when billing automation is connected):
-- INSERT INTO public.community_memberships (user_id, tier, status, starts_at)
-- VALUES ('USER_UUID', 'premium', 'active', NOW())
-- ON CONFLICT (user_id) DO UPDATE SET tier = 'premium', status = 'active', starts_at = NOW(), expires_at = NULL;



-- ============================================================
-- BVS pack 08-final-sprint
-- Source: supabase-final-sprint-core.sql
-- Project: rdwwyolrxahimcgpkzzy
-- Paste entire file into SQL Editor → Run
-- ============================================================

-- BVS final sprint core compatibility migration. Safe to rerun.
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check
  check (role in ('listener','artist','writer','show_creator','moderator','admin'));

alter table public.tracks add column if not exists explicit_content boolean not null default false;

create table if not exists public.track_play_events (
  id bigint generated by default as identity primary key,
  track_id uuid not null references public.tracks(id) on delete cascade,
  source text not null default 'station'
    check (source in ('station', 'catalogue', 'artist', 'embed')),
  created_at timestamptz not null default now()
);

create index if not exists track_play_events_track_created_idx
  on public.track_play_events(track_id, created_at desc);
create index if not exists track_play_events_created_idx
  on public.track_play_events(created_at desc);

alter table public.track_play_events enable row level security;

create or replace function public.record_track_play(p_track_id uuid, p_source text default 'station')
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.track_play_events(track_id, source)
  values (
    p_track_id,
    case when p_source in ('station','catalogue','artist','embed') then p_source else 'station' end
  );

  update public.tracks
  set play_count = coalesce(play_count, 0) + 1
  where id = p_track_id
    and is_public = true
    and editorial_status = 'approved';
end;
$$;
alter table public.orders add column if not exists customer_user_id uuid references auth.users(id) on delete set null;
alter table public.orders add column if not exists tax_amount numeric(10,2) not null default 0;
alter table public.orders add column if not exists tax_rate numeric(8,6) not null default 0;
alter table public.orders add column if not exists tax_mode varchar(40);
alter table public.orders add column if not exists tax_country varchar(8);
alter table public.orders add column if not exists stripe_session_id text;
alter table public.orders add column if not exists stripe_payment_intent text;
create index if not exists orders_customer_user_idx on public.orders(customer_user_id, created_at desc);
create index if not exists orders_stripe_session_idx on public.orders(stripe_session_id) where stripe_session_id is not null;

-- Prevent duplicate credits if webhook requests race.
create unique index if not exists artist_ledger_one_deposit_credit
  on public.artist_ledger_entries(deposit_id, entry_type)
  where deposit_id is not null and entry_type = 'deposit_credit';


