import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import crypto from 'node:crypto';
const read=p=>fs.readFileSync(p,'utf8');
const exports={};
vm.runInNewContext(ts.transpileModule(read('src/lib/newsletter.ts'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports,URL});
for(const path of ['https://evil.test','//evil.test','/\\evil.test','/radio\r\nInjected','/auth/login','/newsletter/click'])assert.throws(()=>exports.newsletterPath(path));
const campaign={id:'example',subject:'Music',body:'<img src=x onerror=alert(1)>\n\nListen now',cta_label:'Listen <now>',cta_path:'/search?mode=fresh#music'};
const destination=new URL(exports.newsletterDestination(campaign));
assert.equal(destination.origin,'https://bvsradio.com');assert.equal(destination.searchParams.get('mode'),'fresh');assert.equal(destination.searchParams.get('utm_campaign'),'example');assert.equal(destination.hash,'#music');
const html=exports.newsletterBody(campaign,'https://bvsradio.com/radio','https://bvsradio.com/newsletter');assert(!html.includes('<img'));assert(html.includes('&lt;img'));assert(html.includes('Unsubscribe'));
const api=read('src/app/api/admin/newsletter/route.ts');assert(api.includes("can(identity,'manage_staff')"));assert(api.includes('subscriber?.is_active'));assert(api.includes("status=eq.queued"));assert(api.includes("status:'uncertain'"));assert(api.includes('escapeEmail(campaign.subject)'));
const sql=read('supabase/migrations/20261008154021_newsletter_workflow.sql');assert(sql.includes('security invoker'));assert(sql.includes('for update'));assert(sql.includes('n<>reviewed_count'));assert(sql.includes('enable row level security'));assert(sql.includes('from anon,authenticated'));
const unsubscribe=read('src/app/newsletter/unsubscribe/route.ts');assert(unsubscribe.includes('export async function POST'));assert(!unsubscribe.split('export async function POST')[0].includes("method:'PATCH'"));
console.log('Newsletter: safe destination, campaign attribution, escaped content, opt-in suppression, owner access, atomic queue and confirmation unsubscribe passed.');
const server={};
vm.runInNewContext(ts.transpileModule(read('src/lib/newsletter-server.ts'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports:server,Buffer,process:{env:{NEWSLETTER_TOKEN_SECRET:'test-only-key'}},require:name=>name==='node:crypto'?crypto:{}});
const id='12345678-1234-1234-1234-123456789abc', token=server.newsletterToken(id);
assert(server.validNewsletterToken(id,token));assert(!server.validNewsletterToken(id,token.slice(1)));assert(!server.validNewsletterToken('bad',token));assert(!server.validNewsletterToken(id,'0'.repeat(64)));
// The helper's pagination is also checked in source because its fetch uses the private Data API.
assert(read('src/lib/newsletter-server.ts').includes('offset+=1000'));
const route={};let allowed=false,mailCalls=0,mutations=[];
const mockRows=async(path,init)=>{if(path.startsWith('newsletter_campaigns?'))return [{...campaign,status:'sending'}];if(path.includes('status=eq.queued')&&init)return [{id}];if(path.includes('status=eq.queued'))return [{id,subscriber_id:id}];if(path.startsWith('newsletter_subscribers?'))return [{email:'test@example.invalid',is_active:false,audience:'listener'}];if(init)mutations.push(JSON.parse(init.body));return [];};
vm.runInNewContext(ts.transpileModule(api,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports:route,require:name=>({'next/server':{NextResponse:{json:(data,init)=>({data,status:init?.status||200})}},'@/lib/editorial-server':{editorialIdentity:async()=>allowed?{user:{id}}:null,can:()=>allowed,audit:async()=>{}},'@/lib/newsletter-server':{newsletterRows:mockRows,newsletterToken:()=>token,newsletterMailReady:()=>true},'@/lib/newsletter':exports,'@/lib/creator-server':{},'@/lib/mailer':{sendBvsEmail:async()=>{mailCalls++},wrapBvsEmailHtml:()=>''}}[name]),Date,Number,JSON,Promise,Error});
assert.equal((await route.POST({json:async()=>({action:'batch',campaignId:id})})).status,403);
allowed=true;
assert.equal((await route.POST({json:async()=>({action:'start',campaignId:id,confirmed:false,reviewedCount:1})})).status,400);
assert.equal((await route.POST({json:async()=>({action:'batch',campaignId:id})})).status,200);
assert.equal(mailCalls,0,'Opted-out recipient must never reach SMTP');assert(mutations.some(m=>m.status==='suppressed'));
console.log('Newsletter tokens reject tampering; owner gate, review gate and runtime opt-out suppression passed without sending email.');
