import Link from 'next/link'
import Image from 'next/image'
import LibraryAction from '@/components/LibraryAction'
import type { DiscoveryItem } from '@/lib/discovery'
import { getPublicArtist } from '@/lib/artist-content'

export default async function ArtistPage({ params }: { params: Promise<{ slug: string }> }) {
  const slug = (await params).slug.toLowerCase()
  const profile = await getPublicArtist(slug)
  if (!profile) return <main className="mx-auto min-h-[65vh] max-w-3xl px-6 py-16 text-center"><p className="text-xs uppercase tracking-[0.25em] text-brand">Artist profiles</p><h1 className="mt-3 text-4xl">This profile is not published yet</h1><p className="mx-auto mt-4 max-w-xl text-text-secondary">BVS publishes artist pages only after editorial verification. We won’t fill the gap with invented tracks, numbers or credits.</p><div className="mt-8 flex justify-center gap-3"><Link href="/catalogue" className="rounded-full bg-brand px-5 py-2 font-semibold text-black">Browse music</Link><Link href="/upload" className="rounded-full border border-white/20 px-5 py-2">Submit music</Link></div></main>

  const item: DiscoveryItem = { id: `artist-${profile.id}`, kind: 'artist', title: profile.name, subtitle: profile.role, href: `/artist/${profile.username}`, image: profile.image }
  return <main className="mx-auto max-w-5xl px-6 py-12"><Link href="/search" className="text-sm text-brand">← Back to discovery</Link><div className="mt-8 flex flex-col gap-10 md:flex-row"><div className="relative aspect-square w-full overflow-hidden rounded-2xl border border-white/10 md:w-80"><Image src={profile.image} alt={profile.name} fill className="object-cover" priority /></div><div className="flex-1"><p className="text-xs uppercase tracking-[0.25em] text-brand">Verified {profile.role}</p><h1 className="mt-2 text-5xl">{profile.name}</h1><p className="mt-5 max-w-prose text-text-secondary">{profile.bio}</p><div className="mt-6"><LibraryAction item={item} section="follows" /></div><section className="mt-10 rounded-2xl border border-white/10 bg-white/[0.03] p-6"><h2 className="text-xl">Published music on BVS</h2>{profile.tracks.length ? <div className="mt-4 space-y-4">{profile.tracks.map(track => <article key={track.id} className="rounded-xl border border-white/10 p-4"><div className="flex justify-between gap-4"><div><h3 className="font-semibold">{track.title}</h3><p className="text-xs text-text-secondary">{track.genre || 'Music'}</p></div><Link href={`/catalogue?q=${encodeURIComponent(track.title)}`} className="text-sm text-brand">Open →</Link></div>{track.credits.length > 0 && <p className="mt-3 border-t border-white/10 pt-3 text-xs text-text-secondary">Verified credits: {track.credits.map(credit => `${credit.person_name} — ${credit.credit_role}`).join(' · ')}</p>}</article>)}</div> : <p className="mt-2 text-sm text-text-secondary">No tracks have been published for this artist yet.</p>}</section></div></div></main>
}
